### ISSUE TITLE
GhostDriver Selenium Node on Windows is broken 

### ISSUE THREAD

**Issue by dhoer** [dhoer/chef-ghostdriver#1]
GhostDriver Selenium Node on Windows is broken until the following issue gets resolved:
https://github.com/detro/ghostdriver/issues/394

**Comment by imakowski** [comment]
Can you fix this issue?

**Comment by dhoer** [comment]
@imakowski This is not a priority for us. Note that detro is looking for maintainers for the ghostdriver project. So if you know of someone interested, please send them his way.

**Comment by dhoer** [comment]
@imakowski I will probably yank support for windows since this issue hasn't been solved in a timely manner.

**Comment by dhoer** [comment]
@imakowski This issue might be fixed with release 1.1.0.  Let me know if it is, or close this issue.
